name: Build and Run Sample Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Uses the self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Build Docker Image
        run: |
          docker build -t sample-image .

      - name: Run Docker Container
        run: |
          docker run -d -p 8080:80 sample-image

