name: Deploy NGINX on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy-nginx:
    runs-on: self-hosted  # Uses the self-hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt update
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Run NGINX container
        run: |
          docker pull nginx:latest
          docker run -d --name nginx -p 80:80 nginx:latest

      - name: Verify NGINX is running
        run: docker ps
