name: Build on test branch changes

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Build Commands
        run: |
          echo "Build triggered due to changes in the satish branch"
          # Add your actual build steps here
